### ISSUE TITLE
When adding new variable, name field remembers previous variable name

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#1]
Когда добавляешь переменную (Variables > Add), поле Name помнит значение предедущей переменной.

Как воспроизвести ошибку:

Надо нажать на существующую переменную (типа поменять её имя), потом вернуться к списку переменных (нажав Cancel, а не Save), и потом можно нажать Add из списка переменных чтобы увидеть проблему.

**Comment by Kimigabuchi** [comment]
Done
https://github.com/ildar-samit/learnix-preview/commit/03795fc8e154a3c15ef4a6d899e00fa63ea87e59
