### ISSUE TITLE
Challenge index page should say "Start Challenge" if not started

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#10]
Right now, the challenge index page says "Resume Challenge" and "Start Over".

Can we make it say "Start Challenge" if the user hasn't started it yet? The button should be blue (`btn-primary` class). After that, it should show those two buttons as it does now.

Also, please change "Start over" to "Start Over". Thanks!

**Comment by Kimigabuchi** [comment]
Try [this](https://github.com/ildar-samit/learnix-preview/commit/750a48c452d51e6b6a6dc66560ae0cd7e4e0cb28)

**Comment by ildar-samit** [comment]
Krasota!
