### ISSUE TITLE
Default code where appropriate

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#12]
Right now, layout shows buttons 0-9, but when you click on a button to edit, the code is empty.

This is a usability problem. For example, users don't know why a button shows "4", but the code is empty. To fix, please have correct code by default, so for button 4, the default code will be: `return 4;`

**Comment by Kimigabuchi** [comment]
[Done](https://github.com/ildar-samit/learnix-preview/commit/401025c29050fd5c91632d511d78b45444a174a3)

**Comment by Kimigabuchi** [comment]
Try [this](https://github.com/ildar-samit/learnix-preview/pull/15/commits/97cfe592775def00f87024fa15448b2ece963f6f)
