### ISSUE TITLE
Variables not working

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#14]
To reproduce:

Create a new variable, give it a name an a value. For example, name it `test`

Then go to layout and edit a box. In code, enter: `return test;`

This gives an error.

**Comment by Kimigabuchi** [comment]
This is not a bug - this is my misunderstanding(( I will correct

**Comment by Kimigabuchi** [comment]
Try [this](https://github.com/ildar-samit/learnix-preview/pull/15/commits/97cfe592775def00f87024fa15448b2ece963f6f)

**Comment by Kimigabuchi** [comment]
[Done](Issue 14. Variables not working)
