### ISSUE TITLE
Add a button to go back to challenge index page

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#3]
The bottom menu should also link to `/app/stage_0/index.html`.

So now it would be:

< Info     |     Layout     |     Variables

**Comment by Kimigabuchi** [comment]
Done
https://github.com/ildar-samit/learnix-preview/commit/b8d8d3f256fa433b05083a0b788c0d0105e41ef2

**Comment by ildar-samit** [comment]
@Kimigabuchi: the button should say "< Info", not "< Index"

**Comment by Kimigabuchi** [comment]
Finally done
https://github.com/ildar-samit/learnix-preview/commit/6296fa4c1ed60204f9b52ebd42c41c1519d7f719
