### ISSUE TITLE
Remove the need to write "return" in variable names

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#7]
When entering a variable name, currently a user has to do this:

```
return my_variable
```

We should have it so that the user types:

```
my_variable
```

So a variable name is just a string, nothing else.

**Comment by Kimigabuchi** [comment]
[Done](https://github.com/ildar-samit/learnix-preview/commit/c02ceafabe39ce5817272fc7ab160a3799032821)
